### ISSUE TITLE
Enhance TapirSupport to generate tapir v1.0 code

### ISSUE THREAD

**Issue by osxhacker** [commercetools/scraml#43]
Hi @adrobisch ,

Tapir has released [v1.0](https://github.com/softwaremill/tapir) since scraml `v0.11.6` was released.  Supporting it requires enhancements to `TapirSupport` AFAIK.  I have forked this repo so that a PR can be made which will address:

- Generating tapir `v1.0.x` compatible code.
- Updating/augmenting existing unit tests.
- Adding a `sbt-test/sbt-scraml/tapir` integration test.
- A `scraml+tapir+refined` code generation defect discovered from above.

Since the code generated would not be source-compatible, I recommend a tag of `v0.12.0` be used if the change-set is accepted.

Also, there may be an opportunity to address the `TODO` documented in `scraml/libs/TapirPackageDefinitions.scala` as well, depending on what new functionality exists in `sttp.tapir.generic.auto`.

If this form of contribution is acceptable, the next issue/PR after this I plan to work on is introducing tapir support for content types in addition to JSON.

**Comment by adrobisch** [comment]
Hi @osxhacker, 
> If this form of contribution is acceptable, the next issue/PR after this I plan to work on is introducing tapir support

:+1: thanks for bringing this up and creating the PR. Will review it asap.

**Comment by osxhacker** [comment]
> Hi @osxhacker,
> 
> > If this form of contribution is acceptable, the next issue/PR after this I plan to work on is introducing tapir support
> 
> 👍 thanks for bringing this up and creating the PR. Will review it asap.

Herr Doktor,

Alles gut, alles klar.  🙇
