### ISSUE TITLE
Enhance TapirSupport to support non-string Params property types

### ISSUE THREAD

**Issue by osxhacker** [commercetools/scraml#47]
Hi @adrobisch ,

Currently, `TapirSupport` unconditionally types properties of the generated path parameters as `String` found [here](https://github.com/commercetools/scraml/blob/d6fb1eaac850330ff039634f7274cd41f30d205b/src/main/scala/scraml/libs/TapirSupport.scala#L87):

```
  private def pathParamsFromResource(resource: Resource): List[Term.Param] =
    resource.getFullUriParameters.asScala.map { uriParam =>
      Term.Param(
        Nil,
        Term.Name(uriParam.getName),
        Some(
          Type.Name("String")
        ),
        None
      )
    }.toList
```

This eliminates typed support for:

- `AnyVal`'s
- enum types

The goal of this enhancement is to enable support for scalar types in addition to `String` for `TapirSupport` generated `Params` types.  I believe this can be accomplished roughly by:

1. Retaining the synthesized `Params` type name as `displayName`.
2. Aggregate the RAML `queryString`, `queryParameters`, `baseUriParameters`, and `uriParameters` of each endpoint (if any) as synthetic `object` properties.
3. Default the `type` of a property to be `string` if no `type` is provided.
4. Fail if the `type` is not a scalar.
5. Generate an in-memory rmf definition.
6. Run each in-memory rmf definition definition through `scraml` code generation, excluding `TapirSupport` and having a fixed `FieldMatchPolicy` of `IgnoreExtra`.
7. Emit the generated `case class`es and `object`s (if needed).

If this approach proves feasible, a PR will follow.  If it is not feasible, the reason(s) why will be added to this issue as a comment for posterity.

**Comment by adrobisch** [comment]
Thanks a lot! I liked the approach from https://github.com/commercetools/scraml/pull/48. Personally,  I could not think about a good example for a complex type in the path param that would justify steps 4 and below. Do you have one? 

This got me thinking if we could have a nicer way to handle templated path params like `/key=somevalue/`, so that it would be possible to type `somevalue`. I can't make a strong case there though, the usages I saw would always have a string-ish value on the right-hand side (but maybe could be good to put constraints/validation there).

**Comment by osxhacker** [comment]
> Thanks a lot! I liked the approach from #48. Personally, I could not think about a good example for a complex type in the path param that would justify steps 4 and below. Do you have one?

The main use-case I can see for steps 5-7 is to enable `RefinedSupport` for the generated `Params` types, thus being able to have atomic validations generated.  Having `CirceSupport` and/or `SphereJsonSupport` could be useful for persisting `Params` as JSON as well (such as for logging requests in a persistent store).  There may be uses for cats and monocle, too, but those are harder for me to envision.

Related to this is issue #13 .  Whether or not all the steps above are incorporated for `Params`, I think the ability to synthesize types is what issue #13 needs.  What do you think?

> This got me thinking if we could have a nicer way to handle templated path params like `/key=somevalue/`, so that it would be possible to type `somevalue`. I can't make a strong case there though, the usages I saw would always have a string-ish value on the right-hand side (but maybe could be good to put constraints/validation there).

PR #48 should enable typing for this if the resource uses `uriParameters`.  For example, if an endpoint such as [stores.raml](https://github.com/commercetools/scraml/blob/4913e94f46812649f991897b21bad8f8d8ff5945/src/sbt-test/sbt-scraml/ct-api/reference/api-specs/api/resources/stores.raml#L42) were:

```
/key={key}/:
  uriParameters:
    key:
      type: integer
```

I could see refined support helping to validate the form of `somevalue` in this example (such as a `string` having `maxLength`, `minLength`, and `pattern` facets).  Using the same resource example as above:

```
/key={key}/:
  uriParameters:
    key:
      type: string
      minLength: 2
      maxLength: 128
      pattern: "^[a-z][a-z0-9.-]+$"
```

The overall form of `/constant={value}/` might benefit from `enum` support for `value`, though as you identified this would most likely not help for `/key=somevalue/` situations.

**Comment by adrobisch** [comment]
> Related to this is issue https://github.com/commercetools/scraml/issues/13 . Whether or not all the steps above are incorporated for Params, I think the ability to synthesize types is what issue https://github.com/commercetools/scraml/issues/13 needs. What do you think?

:+1:  in the context of #13 that makes perfect sense.

> PR https://github.com/commercetools/scraml/pull/48 should enable typing for this if the resource uses uriParameters. For example, if an endpoint such as [stores.raml](https://github.com/commercetools/scraml/blob/4913e94f46812649f991897b21bad8f8d8ff5945/src/sbt-test/sbt-scraml/ct-api/reference/api-specs/api/resources/stores.raml#L42)

:ok_hand: thats nice, was not aware that it would enable that, thanks for all the details!
